yvonneskitchen/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

yvonneskitchen/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('yvonneskitchen.Page.base_views',
        ## Base url ##
        (r'^$', 'home'),

        ## IFrame url ##
        (r'^iframe/(?P<page>.*)/$', 'iframe'),

        ## robots.txt ##
        (r'^robots.txt$', 'robots'),

        ## Admin urls ##
        (r'^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('yvonneskitchen.Page.views',
        ## Home urls ##
        (r'^slideshow/(?P<item_id>\d)/$', 'slideshow'),

        ## Menu urls ##
        (r'^menu/$', 'menu'),
        (r'^menu/(?P<section>sides|breakfast|lunch|dinner|trays-and-platters|desserts|breads-and-pastries)/$', 'menu'),
        (r'^menu/(?P<section>sides|breakfast|lunch|dinner|trays-and-platters|desserts|breads-and-pastries)/(?P<page>\d+)/$', 'menu'),
        (r'^menu/(?P<section>sides|breakfast|lunch|dinner|trays-and-platters|desserts|breads-and-pastries)/(?P<page>\d+)/(?P<estimate_page>\d+)/$', 'menu'),
        (r'^menu/(?P<section>sides|breakfast|lunch|dinner|trays-and-platters|desserts|breads-and-pastries)/(?P<page>\d+)/(?P<estimate_page>\d+)/add/(?P<item_id>\d+)/$', 'menu_add_item'),
        (r'^menu/(?P<section>sides|breakfast|lunch|dinner|trays-and-platters|desserts|breads-and-pastries)/(?P<page>\d+)/(?P<estimate_page>\d+)/remove/(?P<item_id>\d+)/$', 'menu_remove_item'),
        (r'^menu/compute/(?P<section>sides|breakfast|lunch|dinner|trays-and-platters|desserts|breads-and-pastries)/(?P<page>\d+)/(?P<estimate_page>\d+)/$', 'menu_compute_estimate'),

        ## Catering urls ##
        (r'^catering/$', 'catering'),

        ## Delivery urls ##
        (r'^delivery/$', 'delivery'),

        ## About urls ##
        (r'^about/$', 'about'),

        ## Contact urls ##
        (r'^contact/$', 'contact'),
)

urlpatterns += patterns('',
        ####### Static Media Serving #######
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        )

yvonneskitchen/Menu/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce import models as tinymce_models

class MenuItem(models.Model):
    """Model for a menu item"""
    CATEGORY_CHOICES = (
            ('sides', 'Soups Sides & Salads'),
            ('trays-and-platters', 'Trays & Platters'),
            ('breakfast', 'Breakfast Entrees'),
            ('lunch', 'Lunch Entrees'),
            ('dinner', 'Dinner Entrees'),
            ('desserts', 'Desserts'),
            ('breads-and-pastries', 'Breads & Pastries'),
            )

    item_name = models.CharField(
            _('Item Name'),
            max_length = 200
            )

    category = models.CharField(
            _('Category'),
            max_length = 20,
            choices = CATEGORY_CHOICES
            )

    image = models.ImageField(
            _('Image'),
            default = None,
            upload_to = 'img/menu/',
            null = True,
            blank = True
            )

    feature_image = models.ImageField(
            _('Feature Image'),
            default = None,
            upload_to = 'img/menu/',
            null = True,
            blank = True
            )

    featured = models.BooleanField(
            _('Featured'),
            default = False
            )

    description = models.TextField(
            _('Description')
            )

    price = models.DecimalField(
            _('Price'),
            max_digits = 6,
            decimal_places = 2
            )

    per_person_item = models.BooleanField(
            _('Per Person Item'),
            default = True
            )

    weekly_special = models.BooleanField(
            _('Weekly Special'),
            default = False
            )

    special_price = models.DecimalField(
            _('Special Price'),
            max_digits = 6,
            decimal_places = 2
            )

    last_modified = models.DateTimeField(
        _('Date Last Modified'),
        auto_now = True
    )

    def get_hash(self):
        return 'menu'

    def __unicode__(self):
        return self.item_name

    def get_absolute_url(self):
        return '/menu/'

yvonneskitchen/forms.py
from django import forms

import re

class EstimateForm(forms.Form):
    CATERING_OR_DELIVERY = (
            ('none', 'Choose...'),
            ('catered', 'Catered'),
            ('delivery', 'Delivery'),
            )

    service_option = forms.ChoiceField(
            choices = CATERING_OR_DELIVERY
            )

    head_count = forms.IntegerField(
            min_value = 1
            )

    zip_code = forms.CharField(
            max_length = 10
            )

    def clean_service_option(self):
        data = self.cleaned_data['service_option']
        if data == 'none':
            raise forms.ValidationError('Choose catered or delivery.')
        return data

    def clean_zip_code(self):
        data = self.cleaned_data['zip_code']
        if not re.match("\d{5}(-\d{4})?", data):
            raise forms.ValidationError('Invalid zip code format.')
        return data

class WeeklySpecialForm(forms.Form):
    name = forms.CharField(
            max_length = 100,
            required = True
            )

    email_address = forms.EmailField(
            required = True
            )

yvonneskitchen/Menu/views.py
# Create your views here.

yvonneskitchen/templates/menu/menu.html
{% extends "base.html" %}

{% block content %}

    <div id="menu-left">

        <div id="menu-nav">
            <a href="/menu/sides/1/{{estimate_page.number}}/" class="first{%ifequal section "sides"%} selected{%endifequal%}" id="soups-salads-and-sides"></a>
            <a href="/menu/breakfast/1/{{estimate_page.number}}/"{%ifequal section "breakfast"%} class="selected"{%endifequal %} id="breakfast-entrees"></a>
            <a href="/menu/lunch/1/{{estimate_page.number}}/"{%ifequal section "lunch"%} class="selected"{%endifequal %} id="lunch-entrees"></a>
            <a href="/menu/dinner/1/{{estimate_page.number}}/"{%ifequal section "dinner"%} class="selected"{%endifequal %} id="dinner-entrees"></a>
            <a href="/menu/trays-and-platters/1/{{estimate_page.number}}/"{%ifequal section "trays-and-platters"%} class="selected"{%endifequal %} id="trays-and-platters"></a>
            <a href="/menu/breads-and-pastries/1/{{estimate_page.number}}/"{%ifequal section "breads-and-pastries"%} class="selected"{%endifequal %} id="breads-and-pastries"></a>
            <a href="/menu/desserts/1/{{estimate_page.number}}/" class="last{%ifequal section "desserts"%} selected{%endifequal%}" id="desserts"></a>
        </div>

        <div id="menu-estimate">
            <form id="estimate-form" action="/menu/compute/{{section}}/{{menu_page.number}}/{{estimate_page.number}}/" method="post">
                {%csrf_token%}
                {%if estimate_form.service_option.errors%}
                <div class='error'>
                {%endif%}
                <label id="service-option-label" for="id_service_option">Catered or Delivery:</label>{{ estimate_form.service_option }}
                {%if estimate_form.service_option.errors%}
                    {{estimate_form.service_option.errors}}
                </div>
                {%endif%}
                {%if estimate_form.head_count.errors%}
                <div class='error'>
                {%endif%}
                <label id="head-count-label" for="id_head_count">Head Count:</label>{{ estimate_form.head_count }}
                {%if estimate_form.head_count.errors%}
                    {{estimate_form.head_count.errors}}
                </div>
                {%endif%}
                {%if estimate_form.zip_code.errors%}
                <div class='error'>
                {%endif%}
                <label id="zip-code-label" for="id_zip_code">Zip Code:</label>{{ estimate_form.zip_code }}
                {%if estimate_form.zip_code.errors%}
                    {{estimate_form.zip_code.errors}}
                </div>
                {%endif%}

                <h1>Your Menu</h1>
                <h2>Page {{estimate_page.number}} / {{estimate_page.paginator.num_pages}}</h2>

                <div id="selected-items">
                    {% for item in selected_items %}
                        <a href="/menu/{{section}}/{{menu_page.number}}/{{estimate_page.number}}/remove/{{item.id}}/">
                            <h3>{{item.item_name}}</h3>
                            <h4>${%if item.weekly_special%}{{item.special_price|floatformat:2}}{%else%}{{item.price|floatformat:2}}{%endif%}{%if item.per_person_item %} / p{%endif%}</h4>
                        </a>
                    {% empty %}
                        <p>Add items to your menu and complete the above form to get an estimate for your event.</p>
                    {% endfor %}
                </div>

                <div id="estimate-nav-buttons">
                    {%if selected_items_has_previous_page%}
                        <a href="/menu/{{section}}/{{menu_page.number}}/{{estimate_page.previous_page_number}}/" id="previous-page-button">&lt;&lt; Prev</a>
                    {%endif%}

                    <input id="compute-estimate-button" type="submit" value="Compute Estimate"/>
    
                    {%if selected_items_has_next_page%}
                        <a href="/menu/{{section}}/{{menu_page.number}}/{{estimate_page.next_page_number}}/" id="next-page-button">Next &gt;&gt;</a>
                    {%endif%}
                </div>

                {%if estimate_computed%}
                    <h5>Service: <b>${{estimate_service_charge|floatformat:2}}</b></h5><h6>Total: <b>${{estimate_total|floatformat:2}}</b></h6>
                {%endif%}
            </form>
        </div>

    </div>

    <div id="menu-right">

        <div id="menu-header">

            <img src="/media/img/menu-header-{{section}}.png"/>

        </div>

        <div id="menu-item-list">
            {{estimate_list}}

            {% for item in dinner_entrees %}
                <a href="/menu/{{section}}/{{menu_page.number}}/{{estimate_page.number}}/add/{{item.id}}/" class="menu-item">
                    <h1>{{item.item_name}}</h1>
                    <div class="menu-item-thumb" style="background: url('{{item.image.url}}');"></div>
                    <h2>${%if item.weekly_special%}{{item.special_price|floatformat:2}}{%else%}{{item.price|floatformat:2}}{%endif%}{%if item.per_person_item%} / person{%endif%}</h2>
                    <p>{{item.description}}</p>
                    <p class="click-to-add">Click To Add To Your Menu</p>
                </a>
            {% endfor %}

        </div>

        <div id="menu-page-buttons">

            {%if menu_has_previous_page%}
            <a href="/menu/{{section}}/{{menu_page.previous_page_number}}/{{estimate_page.number}}/" id="back-button"></a>
            {%else%}
            <div id="inactive-back-button"></div>
            {%endif%}
            <h2>Page {{menu_page.number}} / {{menu_page.paginator.num_pages}}</h2>
            {%if menu_has_next_page%}
            <a href="/menu/{{section}}/{{menu_page.next_page_number}}/{{estimate_page.number}}/" id="next-button"></a>
            {%else%}
            <div id="inactive-next-button"></div>
            {%endif%}

        </div>
    </div>

{% endblock %}